### ISSUE TITLE
Alternatives to GPT-3 (Can't reproduce because of lack of GPT-3 access)

### ISSUE THREAD

**Issue by NamburiSrinath** [sarahpratt/CuPL#1]
Hi, 

First of all, thanks for the repo :) We are working on something very similar, so we are glad to see some work in this direction.

I tried to replicate this repo, but we don't have access to GPT-3 (currently using Beta version and the rate limit is exceeding, refer Screenshot)

![image](https://user-images.githubusercontent.com/40389487/199852304-22ec4cdb-40a5-4fd8-9727-651cba799156.png)

So, do you have any suggestions on how to generate (automate generating) prompts? We are students, so we can't spend money

Some open source suggestions would be great.

**Comment by sarahpratt** [comment]
Hello! Yes it is not ideal that many of the highest performance LLMs are not open source. I would suggest looking at some of the text generation models on hugging face as an alternative, like GPT-J. These will unfortunately likely have lower performance but can be a good starting point!
